### ISSUE TITLE
Urban Atlas 2018 support ? 

### ISSUE THREAD

**Issue by Doctor-Who** [eea/copernicus_quality_tools#2]
Hi,

Could it be possible to have a version that support Urban Atlas 2018 quality check ? 

Thanks;

**Comment by jirikadlec2** [comment]
Hello, 
If Urban Atlas 2018 is similar to Urban Atlas 2012 (only with different layer names and column names), then we can easily add UA 2018 support.
Can you send us a specification document and / or a sample dataset for Urban Atlas 2018? We need to make sure the attribute names for Urban Atlas 2018 are set-up correctly when we add the new product definition.

Best regards,
Jiří Kadlec

**Comment by Doctor-Who** [comment]
Dear Jiří,

Please find UA2018 specification in attach file : 

[Urban Atlas fields and products renaming for online QC.pdf](https://github.com/eea/copernicus_quality_tools/files/3335302/Urban.Atlas.fields.and.products.renaming.for.online.QC.pdf)

**Comment by Doctor-Who** [comment]
Dear Jiří, Igokr,

Many thanks for your help, the tool now work like a charm. We used it for HRL SWF validation.
About UA2018 support, we need to deliver some area (fua) at the end of September to the EEA.
Will the next release will be available before our due date ? 

Best regards,

Nicolas

**Comment by igokr** [comment]
Dear Nicolas,
we are expecting to release a new version containing UA 2018 at the beginning of the next week.
Best regards,
Igor

**Comment by jirikadlec2** [comment]
Dear Nicolas,
UA 2018 product definitions have been added to QC tool release 1.5.0rc1 (https://github.com/eea/copernicus_quality_tools/releases/tag/1.5.0rc1)

Best regards,
Jiří

**Comment by Doctor-Who** [comment]
We gonna update that this week, many thanks for your notification.

**Comment by Doctor-Who** [comment]
Dear Jiří,

Thanks for update.
UA2018 seems working.
I will open a ticket soon for feedback about missing STL 2018 availability
as the EEA ask a delivery for end of october ...

Best

Nicolas

Le jeu. 19 sept. 2019 à 16:39, Jiří Kadlec <notifications@github.com> a
écrit :

**Comment by jirikadlec2** [comment]
Dear Nicolas,
Regarding the Street Tree (e.g. DE012L1_BREMEN_UA2018_STL) we would like to clarify the field naming in the product definition.

The QC tool will expect STL field names to be:
**country** (String)
**fua_name** (String)
**fua_code** (String)
**stl** (Integer)
**perimeter** (Real)
**area** (Real)

Allowed values of **stl** field are: 1, 0, 91000 or 92000.

Please confirm this is correct.
We are expecting an updated QC tool release with support for STL and for deliveries in GeoPackage (.gpkg) format by start of next week.

Best regards,
Jiří

**Comment by loic-faucqueur** [comment]
Hello Jiří,

I am following up this issue as well.
I can confirm you that your proposition for STL product is correct and that our layers will integrate these fields.

Best,
Loïc

**Comment by jirikadlec2** [comment]
Hello Loïc and Nicolas,
UA 2018 product definitions including the STL product have been updated in QC tool release 1.5.2rc2 (https://github.com/eea/copernicus_quality_tools/releases/tag/1.5.2rc2)

Main changes are:
* File format of UA products can be Geodatabase (.gdb) or Geopackage (.gpkg)
* Two supplementary pdf files (map.pdf and delivery_report.pdf) are required as part of the delivery.
* Product definition for Urban Atlas 2018 Street Tree Layer (ua2018_stl) has been added.
* Sample testing data in .gpkg format including the STL product can be found at https://github.com/eea/copernicus_quality_tools/tree/1.5.2rc2/testing_data/vector/ua/gpkg

Please contact us in case of any questions or issues.

Best regards,

**Comment by Doctor-Who** [comment]
Hi Jiří,
We've updated to latest version 1.5.2rc2
We will get back to you if we've got issue or need adjustment
