### ISSUE TITLE
Pagination doesn't account for filters

### ISSUE THREAD

**Issue by ch-koehler** [eea/copernicus_quality_tools#23]
## Issue

The pagination of the "My deliveries" table doesn't account for filters. Consider the following example:

![grafik](https://github.com/user-attachments/assets/d529e2c7-8c24-4cd2-a512-53c4b39713b7)
No filters set, everything as expected. We've got 16102 rows on 806 pages.

Now let's set a filter:
![grafik](https://github.com/user-attachments/assets/bfd8f25a-563e-4347-9ec5-f477c3aebe51)
The table is being filtered as expected - we have 4 deliveries with a name that matches, but the pagination doesn't update: it still shows us 16102 rows on 806 pages, although - considering the filter - we have only 4 rows on a single page.

When trying to access any other page (i.e. 2 - 806), the frontend gets stuck, apparently trying to load data while there is none:
 
![grafik](https://github.com/user-attachments/assets/66bb4df1-1dc6-4cc9-a8c0-10bc98936d05)

## Expected behavior

Pagination should account for filtered deliveries, so in our example there should just be page `1`.

## System

QC tool version: 2.0.7 container from `eeacms/copernicus-qctool-frontend:2.0.7`.

**Comment by tomicekj** [comment]
@ch-koehler We have just published release 2.0.8, which implements a fix for a filtering bug in pagination deployment (https://github.com/eea/copernicus_quality_tools/releases/tag/2.0.8). Please test it and let me know if it is possible to close this issue.

**Comment by ch-koehler** [comment]
@tomicekj looks good to me! Thank you for the quick fix!
