### ISSUE TITLE
Product and QC Status drop-downs only list values from current page

### ISSUE THREAD

**Issue by ch-koehler** [eea/copernicus_quality_tools#24]
The drop-down list for the filtering options of **Product** and **QC Status** only contain values that occur on the current page.

![grafik](https://github.com/user-attachments/assets/e5aa70fa-6381-4f55-bc09-5969294966cd)

Frontend version 2.0.9.

## Expected behavior

The drop down lists should contain all values, either all possible values or preferably all occurring values in the entire data set.

It used to work for the **Product** filter in 2.0.6 (QC Status was just a free text filter back then):

![grafik](https://github.com/user-attachments/assets/ff15d485-6191-4de7-8078-eca10e49432c)

**Comment by jirikadlec2** [comment]
@ch-koehler Thank you for reporting the issue, we have looked into it and we expect to publish a release with a fix in the coming week Sep 23- Sep 27.
