### ISSUE TITLE
CLCplus checks inconsistencies between EU27 and "normal" product ident

### ISSUE THREAD

**Issue by CLCplusRAS** [eea/copernicus_quality_tools#25]
![image](https://github.com/user-attachments/assets/4d25a748-c856-4f47-87f0-438b09a802a2)

1. When choosing "CLC+ Backbone 2023 raster product (10m) for EU27 AOI" from the product drop down, the raster.naming check fails ("aborted") for tile IDs that start with a "0", like  CLMS_CLCPLUS_RAS_S2023_R10m_E09N27_03035_V01_R00.
_"Layer CLMS_CLCPLUS_RAS_S2023_R10m_E09N27_03035_V01_R00.tif has illegal AOI code e09n27."_
When choosing "CLC+ Backbone 2023 raster product (10m)" the raster.naming check for the same tile is successful.

2. When choosing "CLC+ Backbone 2023 raster product (10m)" from the product drop down, the raster.gap check shows a message _"Check cancelled due to boundary mask file mask_2021_010m_e09n27.tif not available."_ for CLMS_CLCPLUS_RAS_S2023_R10m_E09N27_03035_V01_R00. The check is nevertheless marked as "OK".

3. For other tile IDs that do not start with a "0", the raster.gap check reports a resolution issue _"Resolution of the raster [10.000000, -10.000000] does not match the resolution [10.000000, -10.000000] of the boundary mask 2021eu27.tif."_  when choosing "CLC+ Backbone 2023 raster product (10m) for EU27 AOI" from the product drop down. The check is nevertheless marked as "OK"
In case of choosing "CLC+ Backbone 2023 raster product (10m)", there is no such issue.

**Comment by jirikadlec2** [comment]
Thank you for reporting the issue, we will investigate it and get back to you.

**Comment by jirikadlec2** [comment]
The inconsistencies have been corrected in QC Tool release 2.1.1 (released on November 14 2024) - https://github.com/eea/copernicus_quality_tools/releases/tag/2.1.1
Please be sure to also update the boundary package to the latest boundary package with corrected reference tiles.
