### ISSUE TITLE
Stuck on waiting QC Status

### ISSUE THREAD

**Issue by Doctor-Who** [eea/copernicus_quality_tools#3]
OS Information | openSUSE Leap 15.0
Kernel Version | 4.12.14-lp150.12.45-default
Total CPU | 56
Total memory | 134.8 GB
Docker version | Version | 18.09.1 (API: 1.39)
----------------------------------------------------------

Launch with Docker Compose using 5 workers.

When trying to validate some data such as sample data available on this repository and also our own data, state still stuck on waiting status. 

![Screenshot_20190723_161626](https://user-images.githubusercontent.com/5890416/61720224-a8192380-ad66-11e9-9c63-832780e0fd7a.png)

Log fromworker seems ok : 
```
2019-07-23 10:42:15,792 INFO Set uid to user 0 succeeded
2019-07-23 10:42:15,829 INFO RPC interface 'supervisor' initialized
2019-07-23 10:42:15,830 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2019-07-23 10:42:15,830 INFO RPC interface 'supervisor' initialized
2019-07-23 10:42:15,830 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-07-23 10:42:15,831 INFO supervisord started with pid 1
2019-07-23 10:42:16,926 INFO spawned: 'watcher' with pid 8
2019-07-23 10:42:16,931 INFO spawned: 'postgresql' with pid 9
2019-07-23 10:42:16,934 INFO spawned: 'scheduler' with pid 10
2019-07-23 10:42:18,332 INFO success: watcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-07-23 10:42:19,333 INFO success: postgresql entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2019-07-23 10:42:19,333 INFO success: scheduler entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2019-07-23 10:42:19.528 UTC [9] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-07-23 10:42:19.528 UTC [9] LOG:  listening on IPv6 address "::", port 5432
2019-07-23 10:42:19.562 UTC [9] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-07-23 10:42:19.710 UTC [11] LOG:  database system was shut down at 2019-07-19 16:16:33 UTC
2019-07-23 10:42:19.890 UTC [9] LOG:  database system is ready to accept connections
```
Frontend too ...
```
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying dashboard.0001_initial... OK
  Applying dashboard.0002_delivery_last_job_percent... OK
  Applying dashboard.0003_auto_20181005_0914... OK
  Applying dashboard.0004_auto_20181005_0923... OK
  Applying dashboard.0005_auto_20190219_1601... OK
  Applying dashboard.0006_auto_20190221_1617... OK
  Applying dashboard.0007_auto_20190221_1625... OK
  Applying dashboard.0008_delivery_skip_steps... OK
  Applying dashboard.0009_delivery_worker_url... OK
  Applying dashboard.0010_auto_20190322_1737... OK
  Applying dashboard.0011_auto_20190322_2055... OK
  Applying sessions.0001_initial... OK
Default user guest created successfully.
Default user guest2 created successfully.
Default user guest3 created successfully.
```

Hope you have some clue to help us

**Comment by jirikadlec2** [comment]
1. Can you please check if the workers are running (docker ps should show five running worker containters)
2. Can you please send us a copy of your docker-compose.yml file so we can try to replicate the issue.

Thanks,
Jiří Kadlec

**Comment by Doctor-Who** [comment]
1. Containers are ok 
![Screenshot_20190729_123626](https://user-images.githubusercontent.com/5890416/62042121-9cfa4380-b1fd-11e9-91d1-c22542707f3c.png)
2. See our docker-compose.service_provider.yml :

```
version: '3'

services:
  frontend:
    image: eeacms/copernicus-qctool-frontend
    ports:
      - 8000:8000
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_volume/boundaries
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - WORK_DIR=/mnt/qc_tool_volume/work
      - SUBMISSION_DIR=
      - FRONTEND_DB_PATH=/mnt/qc_tool_volume/frontend.sqlite3
    networks:
      - qc_tool_network
    volumes:
      - /mnt/tmp/UA2018_QC/boundaries:/mnt/qc_tool_boundary/boundaries
      - /mnt/tmp/UA2018_QC/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/tmp/UA2018_QC/work:/mnt/qc_tool_work

  worker:
    image: eeacms/copernicus-qctool-worker
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_volume/boundaries
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - PULL_JOB_URL=http://frontend:8000/pull_job
      - WORK_DIR=/mnt/qc_tool_volume/work
    networks:
      - qc_tool_network
    volumes:
      - /mnt/tmp/UA2018_QC/boundaries:/mnt/qc_tool_boundary/boundaries
      - /mnt/tmp/UA2018_QC/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/tmp/UA2018_QC/work:/mnt/qc_tool_work

volumes:
  qc_tool_volume:
    driver: local

networks:
  qc_tool_network:
    driver: bridge
```

Many thanks for your help

**Comment by jirikadlec2** [comment]
Thank you for sending your docker-compose file. 
I tried running the QC tool with your docker-compose file and the workers also got stuck on "waiting" status.

The problem in your docker-compose.service_provider.yml file is a mismatch between the paths in `environment` and `volumes` sections. Please setup your docker-compose.service_provider.yml as follows:

Option 1: change both `volumes` sections to `- qc_tool_volume:/mnt/qc_tool_volume`

<pre>
version: '3'

services:
  frontend:
    image: eeacms/copernicus-qctool-frontend
    ports:
      - 8000:8000
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_volume/boundaries
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - WORK_DIR=/mnt/qc_tool_volume/work
      - SUBMISSION_DIR=
      - FRONTEND_DB_PATH=/mnt/qc_tool_volume/frontend.sqlite3
    networks:
      - qc_tool_network
    volumes:
      - qc_tool_volume:/mnt/qc_tool_volume

  worker:
    image: eeacms/copernicus-qctool-worker
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_volume/boundaries
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - PULL_JOB_URL=http://frontend:8000/pull_job
      - WORK_DIR=/mnt/qc_tool_volume/work
    networks:
      - qc_tool_network
    volumes:
      - qc_tool_volume:/mnt/qc_tool_volume

volumes:
  qc_tool_volume:
    driver: local

networks:
  qc_tool_network:
    driver: bridge 

</pre>

Option 2: change the values of BOUNDARY_DIR, INCOMING_DIR, WORK_DIR and FRONTEND_DB_PATH in the `environment` sections to match the paths in your `volumes` sections:

<pre>
version: '3'

services:
  frontend:
    image: eeacms/copernicus-qctool-frontend
    ports:
      - 8000:8000
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - WORK_DIR=/mnt/qc_tool_work
      - SUBMISSION_DIR=
      - FRONTEND_DB_PATH=/mnt/qc_tool_work/frontend.sqlite3
    networks:
      - qc_tool_network
    volumes:
      - /mnt/tmp/UA2018_QC/boundaries:/mnt/qc_tool_boundary/boundaries
      - /mnt/tmp/UA2018_QC/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/tmp/UA2018_QC/work:/mnt/qc_tool_work

  worker:
    image: eeacms/copernicus-qctool-worker
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - WORK_DIR=/mnt/qc_tool_work
      - PULL_JOB_URL=http://frontend:8000/pull_job
    networks:
      - qc_tool_network
    volumes:
      - /mnt/tmp/UA2018_QC/boundaries:/mnt/qc_tool_boundary/boundaries
      - /mnt/tmp/UA2018_QC/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/tmp/UA2018_QC/work:/mnt/qc_tool_work

networks:
  qc_tool_network:
    driver: bridge 

</pre>

If the issues persist, please restart the containers with a command such as: 

`docker-compose -f docker-compose.service_provider.yml up -d --scale worker=5 --force-recreate`

This will force the containers to be re-created with the updated volume settings.

Hope this helps,
Jiří

**Comment by Doctor-Who** [comment]
Dear Jiří,

Thanks for your help.
Option 2 will be the best suitable for us. 
When I launch the docker compose, the frontend is not available with lot of django issues.

**Comment by jirikadlec2** [comment]
Can you please send us the error log from the frontend container, does the log contain message "unable to open database file"?

**Comment by Doctor-Who** [comment]
Here is what i've got in container (frontend) log : 

>   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 89, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/sqlite3/base.py", line 383, in execute
>     return Database.Cursor.execute(self, query, params)
> django.db.utils.OperationalError: no such table: dashboard_job
> "GET /pull_job?token=69d219bf-a8be-4b55-82df-4b7d7268559f HTTP/1.1" 500 131404
> Internal Server Error: /pull_job
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/sqlite3/base.py", line 383, in execute
>     return Database.Cursor.execute(self, query, params)
> sqlite3.OperationalError: no such table: dashboard_job

**Comment by jirikadlec2** [comment]
This looks like the frontend database (frontend.sqlite) did not get correctly configured. Can you please try the following docker-compose.yml configuration:

<pre>
version: '3'

services:
  frontend:
    image: eeacms/copernicus-qctool-frontend
    ports:
      - 8000:8000
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - WORK_DIR=/mnt/qc_tool_work
      - SUBMISSION_DIR=
      - FRONTEND_DB_PATH=/mnt/qc_tool_volume/frontend.sqlite3
    networks:
      - qc_tool_network
    volumes:
      - /mnt/tmp/UA2018_QC/boundaries:/mnt/qc_tool_boundary/boundaries
      - /mnt/tmp/UA2018_QC/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/tmp/UA2018_QC/work:/mnt/qc_tool_work
      - qc_tool_volume:/mnt/qc_tool_volume

  worker:
    image: eeacms/copernicus-qctool-worker
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - WORK_DIR=/mnt/qc_tool_work
      - PULL_JOB_URL=http://frontend:8000/pull_job
    networks:
      - qc_tool_network
    volumes:
      - /mnt/tmp/UA2018_QC/boundaries:/mnt/qc_tool_boundary/boundaries
      - /mnt/tmp/UA2018_QC/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/tmp/UA2018_QC/work:/mnt/qc_tool_work

networks:
  qc_tool_network:
    driver: bridge 

volumes:
  qc_tool_volume:
    driver: local
</pre>

Thanks,
Jiří

**Comment by Doctor-Who** [comment]
Jiří your fix works many thanks for your help.
I will ask to our team to test a data validation.
I will get back to you tomorrow for results.

**Comment by Doctor-Who** [comment]
Dear Jiří,

Unfortunately we still had issue. 

Same data on the official portal : 
> Product HRL Small Woody Features, vector + 5m raster
> Reference Year 2015
> File swf_2015_vec_ras_ES_3035_083_full.zip
> Started 2019-07-17T12:11:31Z
> Finished 2019-07-17T13:00:10Z
> Status ok

> Product HRL Small Woody Features, vector + 5m raster
> Reference Year 2015
> File swf_2015_005m_vec_ES_3035_083_full.zip 
> Started 2019-07-30T07:14:08Z
> Finished 2019-07-31T07:33:17Z
> Status error 

`SYSTEM ERROR: Traceback (most recent call last): File "/usr/local/src/copernicus_quality_tools/src/qc_tool/worker/dispatch.py", line 149, in dispatch check_module.run_check(step_params, check_status) File "/usr/local/src/copernicus_quality_tools/src/qc_tool/vector/inspire.py", line 61, in run_check with request.urlopen(req, timeout=60) as resp: File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout) File "/usr/lib/python3.7/urllib/request.py", line 525, in open response = self._open(req, data) File "/usr/lib/python3.7/urllib/request.py", line 543, in _open '_open', req) File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain result = func(*args) File "/usr/lib/python3.7/urllib/request.py", line 1345, in http_open return self.do_open(http.client.HTTPConnection, req) File "/usr/lib/python3.7/urllib/request.py", line 1320, in do_open r = h.getresponse() File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse response.begin() File "/usr/lib/python3.7/http/client.py", line 296, in begin version, status, reason = self._read_status() File "/usr/lib/python3.7/http/client.py", line 257, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/usr/lib/python3.7/socket.py", line 589, in readinto return self._sock.recv_into(b) ConnectionResetError: [Errno 104] Connection reset by peer `

An other product is still running since yesterday (already finished on official portal): 

> Product HRL Small Woody Features, vector + 5m raster
> Reference Year 2015
> File swf_2015_005m_vec_DE_3035_061_full.zip 
> Started 2019-07-30T07:14:08Z
> Finished None
> Status None

![Screenshot_20190731_113448](https://user-images.githubusercontent.com/5890416/62201356-8aac1100-b387-11e9-9a9a-cb4907dd5458.png)

I cannot explain the process take so much time on our server as it has a strong hardware configuration and the average loading is under 4% 

![Screenshot_20190731_113551](https://user-images.githubusercontent.com/5890416/62201368-8ed82e80-b387-11e9-9783-a677bf057578.png)

Thanks

**Comment by igokr** [comment]
Ad Connection reset by peer.

Actual qc tool implementation uses external inspire validation service which has been deprecated.
The availability of such service became unpredictable.

The quickest workaround is to manually turn off inspire check when setting up a new qc job.
This until I turn off the check completely.
And this again until we implement a new check operating on new inspire validation service.
The new service looks far different so the new implementation may not come soon.

Ad long running job

Try F5 on the job result page.
If it reports no result or error, then do GET http://worker_ip:8000/table.json .
The response should give you all jobs just running at the worker.
If the uuid of the job in question is not present, something is broken, while the web frontend is able to detect lost job and should report an error in such case.

vector.mmw and vector.mxmw checks both are applying buffer on all geometries.
The work time should correspond to such operation.

**Comment by Doctor-Who** [comment]
We will do couple of additionnel test asap. Thx for your support.

**Comment by igokr** [comment]
There is a new release 1.4.4 <https://github.com/eea/copernicus_quality_tools/releases/tag/1.4.4>.
It is not needed anymore to disable inspire check manually.

**Comment by Doctor-Who** [comment]
Many thanks, we gonna test that new release asap.
I close that issue as it's working while disable inspire checks. 
140 layers has been upload on our local instance today.
Validation are in progress, I can't test new release at the moment.
